=== MarcGrimme/comoonics-cluster-suite/lib/comoonics/cdsl/test/cdsl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cdsls (cdsl*, defaults)>
<!ATTLIST cdsls config_version CDATA #REQUIRED>

<!ELEMENT cdsl (nodes)>
<!ATTLIST cdsl
  src CDATA #REQUIRED
  type CDATA #REQUIRED
  timestamp CDATA #REQUIRED>

<!ELEMENT nodes (noderef*)>

<!ELEMENT noderef EMPTY>
<!ATTLIST noderef
  ref IDREF #REQUIRED>

<!ELEMENT defaults (nodesdefault*)>
<!ATTLIST defaults
  cdsltree CDATA #REQUIRED
  cdsltree_shared CDATA #REQUIRED
  cdsl_link CDATA #REQUIRED
  root CDATA #IMPLIED
  mountpoint CDATA #IMPLIED
  default_dir CDATA #IMPLIED
  maxnodeidnum CDATA #REQUIRED
  node_prefix CDATA #IMPLIED
  use_nodeids CDATA #REQUIRED>

<!ELEMENT nodesdefault (nodedefault*)>

<!ELEMENT nodedefault EMPTY>
<!ATTLIST nodedefault
  id ID #REQUIRED
  cdsltree CDATA #IMPLIED
  cdsltree_shared CDATA #IMPLIED
  cdsl_link CDATA #IMPLIED
  root CDATA #IMPLIED
  mountpoint CDATA #IMPLIED
  default_dir CDATA #IMPLIED
  maxnodeidnum CDATA #IMPLIED
  node_prefix CDATA #IMPLIED
  use_nodeids CDATA #IMPLIED>

=== MarcGrimme/comoonics-cluster-suite/lib/comoonics/cdsl/test/cdsl4.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE cdsls SYSTEM "/home/andrea/python_workspace/CDSL_Tools/lib/comoonics/cdsl/test/cdsl.dtd">
<cdsls config_version='1'>
  <cdsl src='/something' timestamp='1176470424.11' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
      <noderef ref='gfs-node7'/>
      <noderef ref='gfs-node7'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent' timestamp='1185971913.72' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/something' timestamp='1176470424.11' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
      <noderef ref='gfs-node7'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent' timestamp='1184919462.58' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent/shared' timestamp='1185971913.74' type='shared'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent/shared/hostdependent_subdir' timestamp='1185971913.76' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent/shared/hostdependent_subdir/shared_subdir' timestamp='1185971913.79' type='shared'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent/shared/hostdependent_file' timestamp='1185969589.23' type='hostdependent'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <cdsl src='/hostdependent/shared/hostdependent_subdir/shared_file' timestamp='1185969418.8' type='shared'>
    <nodes>
      <noderef ref='gfs-node1'/>
      <noderef ref='gfs-node2'/>
      <noderef ref='gfs-node4'/>
    </nodes>
  </cdsl>
  <defaults use_nodeids='False' mountpoint='/home/andrea/test' cdsltree_shared='cluster/shared' cdsl_link='/cdsl.local' maxnodeidnum='0' cdsltree='cluster/cdsl'>
    <nodesdefault>
      <nodedefault id='gfs-node1'/>
      <nodedefault id='gfs-node2'/>
      <nodedefault id='gfs-node4'/>
      <nodedefault id='gfs-node7'/>
    </nodesdefault>
  </defaults>
</cdsls>
